# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Postman Test Run

on:
  push:
    branches: [ ns/postman ]
  pull_request:
    branches: [ ns/postman ]
  repository_dispatch:
    types: [ deploy_success ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  

    - name: Install dependencies
      run: |
        npm install newman

    - name: Test
      run: |
        node_modules/.bin/newman run test/test_collection.json -e test_env.json 

    

   

  
